### ISSUE TITLE
source-aws aws-sdk-v3 support

### ISSUE THREAD

**Issue by jconnolly-bond** [blacha/chunkd#88]
`.promise()` is not supported in v3 calls, are there any plans for v3 sdk compatibility? 

The v3 API still support v2-eque calls like `.getObject` but the main difference seems to be that `.promise` is no longer supported or required for async requests.

i.e
```
// v2
const resp = await this.remote.getObject({ Bucket: this.bucket, Key: this.key, Range: fetchRange }).promise();

// v3
const resp = await this.remote.getObject({ Bucket: this.bucket, Key: this.key, Range: fetchRange });
```

Thanks very much

**Comment by blacha** [comment]
I am not currently using the v3 SDK as I actually thought it was still in beta!

now looking at it, I might switch more of my stuff across to the v3 api, so Ill look to make this compatible with both v2 and v3 in the next few days.

Thanks for raising the issue!

**Comment by jconnolly-bond** [comment]
Thanks for your reply, that sounds perfect.

**Comment by blacha** [comment]
So after looking at the v3 sdk api, Looks like its simplest to create a wrapper around it and return v2 like objects.


The interface is 

```typescript
import { SourceAwsS3 } from '@chunkd/source-aws';
import { S3LikeV3 } from '@chunkd/source-aws-v3';
import { S3Client } from '@aws-sdk/clients-s3';
const s3 = new new S3Client()
const source = new SourceAwsS3('bucket', 'path/to/cog.tif', new S3LikeV3(s3)));
// Load the first 1KB
await source.fetchBytes(0, 1024);
```

Does this API change work for you?

I need to do a bit more work to remove the dependency on `aws-sdk` from `@chunkd/source-aws` still and Ill convert  `@chunkd/fs` to the v3 sdk.

**Comment by jconnolly-bond** [comment]
This seems reasonable and looks like it would fit perfectly with our existing s3 configuration. 

Thanks very much!
